###############################################################
# Makefile simplificado para compilar programas 
# para stm32 usando a biblioteca libopencm3
# Nao usa scripts especialisados de sistemas posix (Linux)
# Com estas modificacoes pode-se compilar programas no cmd do windows.
# FENG-PUCRS Laboratorio de Processadores 2016-2
# Escrito por Marcos Augusto Stemmer
# Este arquivo pode ser usado, copiado ou modificado livremente.
################################################################
TARGET	 = touch-lcd
CSOURCES = main.c uart-int.c sdram.c mprintf.c ili9341c.c i2c3_touch.c
ASOURCES =
HEADERS	 = ili9341.h sdram.h uart.h
include ../Makefile.include